### ISSUE TITLE
send log error

### ISSUE THREAD

**Issue by LiangLuDev** [octavian-h/appcenter_sdk_plus#1]
send log connect timeout

**Comment by octavian-h** [comment]
Are you referring to logging connection timeouts? For example here: https://github.com/octavian-h/appcenter_sdk_plus/blob/950025f85bef9db42fa1f9eae2da800823ad893d/lib/infrastructure/appcenter/appcenter_client.dart#L32 ?

**Comment by LiangLuDev** [comment]
yep，I made sure I filled in the api key correctly，but the request failed

**Comment by octavian-h** [comment]
I have added more logs in the new release.
